version: '3.8'

services:
  postgres-db:
    image: postgres:17
    container_name: car-rental-db
    environment:
      POSTGRES_DB: car_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - car-rental-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  car-rental-network:
    driver: bridge